# Generated by Django 2.0.2 on 2018-09-03 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area_local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Centro_comercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_centro', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Combos_promos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='SOME STRING', max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('compros', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.Area_local')),
            ],
        ),
        migrations.AddField(
            model_name='area_local',
            name='locales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.Centro_comercial'),
        ),
    ]
