# Generated by Django 2.0.2 on 2018-09-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admincc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='BigBoss', max_length=100)),
                ('ccs', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.Centro_comercial')),
                ('locales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.Area_local')),
            ],
        ),
        migrations.AlterField(
            model_name='combos_promos',
            name='nombre',
            field=models.CharField(default='Mi primer combo', max_length=100),
        ),
    ]
