# Generated by Django 2.0.2 on 2018-09-14 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miapp', '0003_admincc_compros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('escc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.Centro_comercial')),
                ('eslocal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.Area_local')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
