# Generated by Django 2.0.2 on 2018-06-20 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleccion',
            old_name='pregunta',
            new_name='preguntas',
        ),
    ]
